apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-mongo
  namespace: api
spec:
  selector:
    matchLabels:
      app: api-mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: api-mongo
    spec:
      containers:
        - name: api-mongo
          image: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "mongodb"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "mongodb"
          ports:
            - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: api-mongo
  namespace: api
spec:
  type: NodePort
  selector:
    app: api-mongo
  ports:
    - port: 27017
