apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-api
  namespace: api
spec:
  selector:
    matchLabels:
      app: prediction-api
  replicas: 2
  template:
    metadata:
      labels:
        app: prediction-api
    spec:
      containers:
        - name: prediction-api
          image: localhost:5000/api-prediction-api:latest
          env:
            - name: ISS
              value: "http://login-api.login"
            - name: DATABASE_CONNECTION
              value: "mongodb://mongodb:mongodb@api-mongo:27017"
            - name: REDIS_URL
              value: "redis.training"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: prediction-api
  namespace: api
spec:
  selector:
    app: prediction-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
