apiVersion: apps/v1
kind: Deployment
metadata:
  name: lakefs
  namespace: training
spec:
  selector:
    matchLabels:
      app: lakefs
  replicas: 1
  template:
    metadata:
      labels:
        app: lakefs
    spec:
      containers:
        - name: lakefs
          image: treeverse/lakefs:latest
          command: [
            "lakefs run --quickstart"
          ]
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: lakefs
  namespace: training
spec:
  selector:
    app: lakefs
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
