apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-postgres
  namespace: login
spec:
  selector:
    matchLabels:
      app: login-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: login-postgres
    spec:
      containers:
        - name: login-postgres
          image: postgres:17-alpine
          env:
            - name: DATA_SOURCE_NAME
              value: "postgresql://login:login@login-postgres:5432/login?sslmode=disable"
            - name: POSTGRES_USER
              value: "login"
            - name: POSTGRES_PASSWORD
              value: "login"
            - name: POSTGRES_DB
              value: "login"
          ports:
            - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: login-postgres
  namespace: login
spec:
  type: NodePort
  selector:
    app: login-postgres
  ports:
    - port: 5432
