apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-api
  namespace: login
spec:
  selector:
    matchLabels:
      app: login-api
  replicas: 1
  template:
    metadata:
      labels:
        app: login-api
    spec:
      containers:
        - name: login-api
          image: localhost:5000/login-login-api:latest
          env:
            - name: ISS
              value: "http://login-api.login"
            - name: DATABASE_CONNECTION
              value: "postgresql://login:login@login-postgres:5432"
            - name: PYWAY_DATABASE_MIGRATION_DIR
              value: "migration"
            - name: PYWAY_TABLE
              value: "pyway"
            - name: PYWAY_TYPE
              value: "postgres"
            - name: PYWAY_DATABASE_HOST
              value: "login-postgres"
            - name: PYWAY_DATABASE_PORT
              value: "5432"
            - name: PYWAY_DATABASE_NAME
              value: "login"
            - name: PYWAY_DATABASE_USERNAME
              value: "login"
            - name: PYWAY_DATABASE_PASSWORD
              value: "login"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: login-api
  namespace: login
spec:
  selector:
    app: login-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
